name: Deploy MkDocs

on:
  pull_request:
    branches:
      - '**' 

jobs:
  deploy-pr:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: |
          pip install poetry

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Deploy to GitHub Pages (Pull Request)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

          poetry run mike deploy --push --update-aliases develop latest
          poetry run mike set-default --push latest

